language: python
os: linux
arch:
  - amd64
  - x86_64
 # - ppc64le
 # - s390x
 # - arm64
python:
  - 3.6
  - 3.7
jobs:
  include:
    # ======= OSX ========
#     ----- changes in Travis images means this doesn't work for versions before 3.7.5 ---
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode11.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
      script: echo "works"
    #  ====== WINDOWS =========
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - apt update
  - apt install -y software-properties-common
  - apt update
  - apt-get install -y --no-install-recommends build-essential gcc

install:
  - python --version
#   - pip install -U pip
#   - pip3 install -U -r requirements/core.txt
  - python setup.py install
script: echo "works" # run tests
